### ISSUE TITLE
Deleting collections makes system unsearchable

### ISSUE THREAD

**Issue by awead** [psu-libraries/cho#542] opened 2018-06-11 20:19 UTC
If I delete a collection that has works, I'm unable to perform any searches, and I get a 404 error. This is probably related to the fact that search results for works display the collection name and link, which if not present, would explain the 404.

Either we should allow for orphaned works, or probably the better solution is to only allow deleting empty collections.

Connected #509

**Comment by ntallman** [comment] 2018-06-11 20:44
Related / Dupe of #509?

**Closed** 2019-02-25 15:58 UTC
Labels: MVP, bug, refine
