### ISSUE TITLE
The piwik id should change based on server

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/cho#951] opened 2019-04-10 16:17 UTC
It is hard coded to 2, which is the QA id number.  Stage is 5 and prod is 6.
https://github.com/psu-libraries/cho/blob/77f948eb8c7c38826a681f1ecc3275acc1e244f1/app/assets/javascripts/matomo.js#L12

**Comment by awead** [comment] 2019-06-07 14:00
TODO:
* make this a deployment-side configuration change, likely with Figaro environment variables
* do this how we're doing it Scholarsphere
* testing should include deploying to QA and staging to verify that it's working

**Comment by rschenk** [comment] 2019-06-12 17:24
I looked into doing this with Figaro, i.e. `application.yml` and indeed, it looks like this will be the place to do it. The `application.yml` file is one of the linked_files in the Capistrano, which I infer to mean that it's written by Chef and symlinked in after deploy. 

To do this, we'll need to add a key into the application.yml code and some minimal ERB to insert it into the javascript, but most of the effort will be involved talking to devops people to get the appropriate piwik ids into the respective Chef configs.

**Comment by ntallman** [comment] 2019-07-03 15:19
Confirmed to be correct in production!

**Closed by ntallman** 2019-07-03 15:19 UTC
Labels: 2-points, MVP, MVP-8, administration, devops
